server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: multiple-instances3
          uri: https://github.com/JavierGarcia2727/microserviciosLaTegnologia
          search-paths: config-data
  application:
    name: config-service 
  
